In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.preprocessing import MinMaxScaler

In [2]:
df = pd.read_csv("anime.csv")
df.head()

,anime_id,name,genre,type,episodes,rating,members
0,32281,Kimi no Na wa.,"Drama, Romance, School, Supernatural",Movie,1,9.37,200630
1,5114,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",TV,64,9.26,793665
2,28977,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.25,114262
3,9253,Steins;Gate,"Sci-Fi, Thriller",TV,24,9.17,673572
4,9969,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",TV,51,9.16,151266

In [3]:
df.info()
df.describe()
df.isnull().sum()
df = df.dropna()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12294 entries, 0 to 12293
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   anime_id  12294 non-null  int64
 1   name      12294 non-null  object
 2   genre     12232 non-null  object
 3   type      12269 non-null  object
 4   episodes  12294 non-null  object
 5   rating    12064 non-null  float64
 6   members   12294 non-null  int64
dtypes: float64(1), int64(2), object(4)
memory usage: 672.5+ KB

In [4]:
df = df[['name', 'genre', 'rating', 'members']]
df.head()

,name,genre,rating,members
0,Kimi no Na wa.,"Drama, Romance, School, Supernatural",9.37,200630
1,Fullmetal Alchemist: Brotherhood,"Action, Adventure, Drama, Fantasy, Magic, Mili...",9.26,793665
2,Gintama°,"Action, Comedy, Historical, Parody, Samurai, S...",9.25,114262
3,Steins;Gate,"Sci-Fi, Thriller",9.17,673572
4,Gintama&#039;,"Action, Comedy, Historical, Parody, Samurai, S...",9.16,151266

In [5]:
genre_dummies = df['genre'].str.get_dummies(sep=',')

In [6]:
features = pd.concat([genre_dummies, df[['rating', 'members']]], axis=1)

In [14]:
features.head

<bound method NDFrame.head of         Adventure   Cars   Comedy   Dementia   Demons   Drama   Ecchi  \
0               0      0        0          0        0       0       0
1               1      0        0          0        0       1       0
2               0      0        1          0        0       0       0
3               0      0        0          0        0       0       0
4               0      0        1          0        0       0       0
...           ...    ...      ...        ...      ...     ...     ...
12289           0      0        0          0        0       0       0
12290           0      0        0          0        0       0       0
12291           0      0        0          0        0       0       0
12292           0      0        0          0        0       0       0
12293           0      0        0          0        0       0       0

        Fantasy   Game   Harem  ...  Slice of Life  Space  Sports  \
0             0      0       0  ...              0      0       0
1             1      0       0  ...              0      0       0
2             0      0       0  ...              0      0       0
3             0      0       0  ...              0      0       0
4             0      0       0  ...              0      0       0
...         ...    ...     ...  ...            ...    ...     ...
12289         0      0       0  ...              0      0       0
12290         0      0       0  ...              0      0       0
12291         0      0       0  ...              0      0       0
12292         0      0       0  ...              0      0       0
12293         0      0       0  ...              0      0       0

       Super Power  Supernatural  Thriller  Vampire  Yaoi    rating   members
0                0             0         0        0     0  0.924370  0.197867
1                0             0         0        0     0  0.911164  0.782769
2                0             0         0        0     0  0.909964  0.112683
3                0             0         0        0     0  0.900360  0.664323
4                0             0         0        0     0  0.899160  0.149180
...            ...           ...       ...      ...   ...       ...       ...
12289            0             0         0        0     0  0.297719  0.000196
12290            0             0         0        0     0  0.313325  0.000169
12291            0             0         0        0     0  0.385354  0.000204
12292            0             0         0        0     0  0.397359  0.000161
12293            0             0         0        0     0  0.454982  0.000128

[12017 rows x 84 columns]>

In [7]:
scaler = MinMaxScaler()
features[['rating', 'members']] = scaler.fit_transform(features[['rating', 'members']])

In [16]:
features.head

<bound method NDFrame.head of         Adventure   Cars   Comedy   Dementia   Demons   Drama   Ecchi  \
0               0      0        0          0        0       0       0
1               1      0        0          0        0       1       0
2               0      0        1          0        0       0       0
3               0      0        0          0        0       0       0
4               0      0        1          0        0       0       0
...           ...    ...      ...        ...      ...     ...     ...
12289           0      0        0          0        0       0       0
12290           0      0        0          0        0       0       0
12291           0      0        0          0        0       0       0
12292           0      0        0          0        0       0       0
12293           0      0        0          0        0       0       0

        Fantasy   Game   Harem  ...  Slice of Life  Space  Sports  \
0             0      0       0  ...              0      0       0
1             1      0       0  ...              0      0       0
2             0      0       0  ...              0      0       0
3             0      0       0  ...              0      0       0
4             0      0       0  ...              0      0       0
...         ...    ...     ...  ...            ...    ...     ...
12289         0      0       0  ...              0      0       0
12290         0      0       0  ...              0      0       0
12291         0      0       0  ...              0      0       0
12292         0      0       0  ...              0      0       0
12293         0      0       0  ...              0      0       0

       Super Power  Supernatural  Thriller  Vampire  Yaoi    rating   members
0                0             0         0        0     0  0.924370  0.197867
1                0             0         0        0     0  0.911164  0.782769
2                0             0         0        0     0  0.909964  0.112683
3                0             0         0        0     0  0.900360  0.664323
4                0             0         0        0     0  0.899160  0.149180
...            ...           ...       ...      ...   ...       ...       ...
12289            0             0         0        0     0  0.297719  0.000196
12290            0             0         0        0     0  0.313325  0.000169
12291            0             0         0        0     0  0.385354  0.000204
12292            0             0         0        0     0  0.397359  0.000161
12293            0             0         0        0     0  0.454982  0.000128

[12017 rows x 84 columns]>

In [17]:
similarity_matrix = cosine_similarity(features)
similarity_df = pd.DataFrame(
    similarity_matrix,
    index=df['name'],
    columns=df['name']
)
similarity_df.head()

name,Kimi no Na wa.,Fullmetal Alchemist: Brotherhood,Gintama°,Steins;Gate,Gintama&#039;,Haikyuu!!: Karasuno Koukou VS Shiratorizawa Gakuen Koukou,Hunter x Hunter (2011),Ginga Eiyuu Densetsu,Gintama Movie: Kanketsu-hen - Yorozuya yo Eien Nare,Gintama&#039;: Enchousen,...,Silent Chaser Kagami,Super Erotic Anime,Teleclub no Himitsu,Tenshi no Habataki Jun,The Satisfaction,Toushindai My Lover: Minami tai Mecha-Minami,Under World,Violence Gekiga David no Hoshi,Violence Gekiga Shin David no Hoshi: Inma Densetsu,Yasuji no Pornorama: Yacchimae!!
name,,,,,,,,,,,,,,,,,,,,,
Kimi no Na wa.,1.000000,0.155129,0.139392,0.241579,0.139034,0.346482,0.184555,0.379767,0.135737,0.136158,...,0.153103,0.132291,0.141599,0.127127,0.128855,0.119250,0.124951,0.150271,0.154318,0.173060
Fullmetal Alchemist: Brotherhood,0.155129,1.000000,0.358559,0.255805,0.361090,0.412497,0.639303,0.294580,0.353486,0.354359,...,0.114914,0.099297,0.106288,0.095438,0.096728,0.089528,0.093802,0.112809,0.115838,0.129895
Gintama°,0.139392,0.358559,1.000000,0.177076,0.999908,0.270650,0.458125,0.296822,0.999874,0.999916,...,0.119066,0.102880,0.110118,0.098862,0.100207,0.092736,0.097171,0.116861,0.120010,0.134586
Steins;Gate,0.241579,0.255805,0.177076,1.000000,0.180066,0.199986,0.269741,0.216826,0.168883,0.170175,...,0.182958,0.158093,0.169222,0.151943,0.153999,0.142534,0.149340,0.179600,0.184426,0.206810
Gintama&#039;,0.139034,0.361090,0.999908,0.180066,1.000000,0.269883,0.459322,0.295911,0.999613,0.999693,...,0.117729,0.101725,0.108882,0.097753,0.099082,0.091696,0.096080,0.115550,0.118662,0.133074

In [18]:
def recommend_anime(anime_name, top_n=5):

    if anime_name not in similarity_df.index:
        return "Anime not found"

    scores = similarity_df[anime_name]

    scores = scores.sort_values(ascending=False)

    scores = scores[1:top_n+1]

    return scores

In [19]:
recommend_anime("Naruto")

name
Naruto: Shippuuden                                       0.998222
Naruto: Shippuuden Movie 4 - The Lost Tower              0.970475
Naruto: Shippuuden Movie 3 - Hi no Ishi wo Tsugu Mono    0.970356
Boruto: Naruto the Movie                                 0.969445
Naruto x UT                                              0.963998
Name: Naruto, dtype: float64

In [20]:
def recommend_with_threshold(anime_name, threshold=0.5):

    if anime_name not in similarity_df.index:
        return "Anime not found"

    scores = similarity_df[anime_name]

    scores = scores[scores > threshold]

    scores = scores.sort_values(ascending=False)

    scores = scores[1:]

    return scores

In [21]:
print("Recommendations with Threshold = 0.95")
recommend_with_threshold("Naruto", threshold=0.95)

Recommendations with Threshold = 0.95

name
Naruto: Shippuuden                                                           0.998222
Naruto: Shippuuden Movie 4 - The Lost Tower                                  0.970475
Naruto: Shippuuden Movie 3 - Hi no Ishi wo Tsugu Mono                        0.970356
Boruto: Naruto the Movie                                                     0.969445
Naruto x UT                                                                  0.963998
Naruto Soyokazeden Movie: Naruto to Mashin to Mitsu no Onegai Dattebayo!!    0.963705
Boruto: Naruto the Movie - Naruto ga Hokage ni Natta Hi                      0.963296
Naruto Shippuuden: Sunny Side Battle                                         0.962542
Name: Naruto, dtype: float64

In [22]:
print("Recommendations with Threshold = 0.80")
recommend_with_threshold("Naruto", threshold=0.80)

Recommendations with Threshold = 0.80

name
Naruto: Shippuuden                                                           0.998222
Naruto: Shippuuden Movie 4 - The Lost Tower                                  0.970475
Naruto: Shippuuden Movie 3 - Hi no Ishi wo Tsugu Mono                        0.970356
Boruto: Naruto the Movie                                                     0.969445
Naruto x UT                                                                  0.963998
Naruto Soyokazeden Movie: Naruto to Mashin to Mitsu no Onegai Dattebayo!!    0.963705
Boruto: Naruto the Movie - Naruto ga Hokage ni Natta Hi                      0.963296
Naruto Shippuuden: Sunny Side Battle                                         0.962542
Katekyo Hitman Reborn!                                                       0.896261
Kyutai Panic Adventure!                                                      0.861483
Battle Spirits: Ryuuko no Ken                                                0.859171
Dragon Ball Z                                                                0.854969
Dragon Ball Kai                                                              0.835412
Dragon Ball Super                                                            0.832975
Bleach                                                                       0.832259
Medaka Box                                                                   0.832061
Tenjou Tenge                                                                 0.830996
Medaka Box Abnormal                                                          0.829883
Dragon Ball Kai (2014)                                                       0.828921
Dragon Ball Z Movie 15: Fukkatsu no F                                        0.827164
Dragon Ball GT: Goku Gaiden! Yuuki no Akashi wa Suushinchuu                  0.822790
Dragon Ball Z Movie 11: Super Senshi Gekiha!! Katsu no wa Ore da             0.821834
Dragon Ball Z: Summer Vacation Special                                       0.821465
Dragon Ball Z: Atsumare! Gokuu World                                         0.820614
Boku no Hero Academia                                                        0.815836
Shijou Saikyou no Deshi Kenichi                                              0.802611
Bleach Movie 3: Fade to Black - Kimi no Na wo Yobu                           0.800605
Name: Naruto, dtype: float64

In [23]:
print("Recommendations with Threshold = 0.50")
recommend_with_threshold("Naruto", threshold=0.50)

Recommendations with Threshold = 0.50

name
Naruto: Shippuuden                                              0.998222
Naruto: Shippuuden Movie 4 - The Lost Tower                     0.970475
Naruto: Shippuuden Movie 3 - Hi no Ishi wo Tsugu Mono           0.970356
Boruto: Naruto the Movie                                        0.969445
Naruto x UT                                                     0.963998
                                                                  ...
Top wo Nerae! Gunbuster                                         0.500871
Fullmetal Alchemist: The Sacred Star of Milos                   0.500689
Inishie no Megami to Houseki no Ite                             0.500389
Growlanser IV: Wayfarer of the Time                             0.500175
Studio Khara vs. CyberConnect2 Gachinko! Animation Taiketsu!    0.500084
Name: Naruto, Length: 816, dtype: float64

In [24]:

Observation

Threshold = 0.95
Very few recommendations
Highly similar anime only

Threshold = 0.80
Balanced recommendations
Good accuracy and diversity

Threshold = 0.50
More recommendations
Includes less similar anime

Conclusion
Threshold selection controls
recommendation quality and quantity.

SyntaxError: unterminated triple-quoted string literal (detected at line 19) (3990338434.py, line 19)

In [25]:
#Q1
User-Based Collaborative Filtering:
Recommends items based on similar users.
If User A and User B have similar interests,
items liked by User B are recommended to User A.

Example
User A likes Naruto and One Piece.
User B likes Naruto, One Piece, and Bleach.
System recommends Bleach to User A.

Advantages:
Personalized recommendations

Disadvantages:
Slow for large datasets


Item-Based Collaborative Filtering:
Recommends items based on item similarity.
If a user likes Naruto,
similar anime are recommended.

Example
Naruto is similar to Bleach and One Piece.
System recommends them

Advantages:
Faster and scalable
Stable recommendations

Disadvantages:
Needs item similarity computation

'\nQ1. Difference Between User-Based and Item-Based Collaborative Filtering\n\nUser-Based Collaborative Filtering:\n- Recommends items based on similar users.\n- If User A and User B have similar interests,\n  items liked by User B are recommended to User A.\n\nExample:\nUser A likes Naruto and One Piece.\nUser B likes Naruto, One Piece, and Bleach.\nSystem recommends Bleach to User A.\n\nAdvantages:\n- Personalized recommendations\n\nDisadvantages:\n- Slow for large datasets\n\n\nItem-Based Collaborative Filtering:\n- Recommends items based on item similarity.\n- If a user likes Naruto,\n  similar anime are recommended.\n\nExample:\nNaruto is similar to Bleach and One Piece.\nSystem recommends them.\n\nAdvantages:\n- Faster and scalable\n- Stable recommendations\n\nDisadvantages:\n- Needs item similarity computation\n\nThis assignment uses Item-Based Collaborative Filtering.\n'

In [ ]:
#Q2

Collaborative Filtering is a recommendation technique
that suggests items based on user behavior and similarity.

Working Steps

1. Collect user-item interaction data
   Example:
   ratings, watch history, likes

2. Create feature matrix

3. Calculate similarity
   - User similarity or
   - Item similarity

4. Recommend items with highest similarity


Types:
1. User-Based Collaborative Filtering
2. Item-Based Collaborative Filtering

Advantages:
Personalized recommendations
No need for detailed item information

Disadvantages:
Cold start problem
Sparse data issue
Scalability challenges